#!/bin/bash

LAB=$1
STEP=$2

if [[ $# == 0 ]]
    then
	printf "\n Need help in an instructor lead class?  Enter your request like this:
    ASK FOR HELP:  live-help LAB# STEP#
    EXAMPLE: live-help 6 20\n
    To CLEAR a request for help, enter: live-help clear\n\n"
	  exit 0
fi

if [[ $LAB =~ clear ]]
    then
      printf " \n Trouble request CLEARED \n\n"
    exit 0
fi


if ! [[ $LAB =~ ^[0-9]+$ ]] 
  then
    printf "\n SORRY! Your first parameter was NOT a number, enter your help request like this:
	  FORMAT:  live-help LAB# STEP#
	  EXAMPLE: live-help 6 20\n\n"
    exit 0
  else
    PARAM1=true
fi


if ! [[ $STEP =~ ^[0-9]+$ ]] 
  then
    printf "\n SORRY! Your second parameter was NOT a number, enter your help request like this:
	  FORMAT:  live-help LAB# STEP#
	  EXAMPLE: live-help 6 20\n\n"
    exit 0
  else
    PARAM2=true
fi

if [[ $PARAM1 = true && $PARAM2 = true ]]
  then
    printf "\n Your request for help on LAB: $LAB  STEP: $STEP has been sent\n\n"
fi


